CREATE TABLE `user` (
    id INT(100) NOT NULL PRIMARY KEY AUTO_INCREMENT,
    firstname VARCHAR() NOT NULL,
    secondname VARCHAR() NOT NULL,
    email VARCHAR() NOT NULL,
    password VARCHAR() NOT NULL,
    date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
);